### ISSUE TITLE
AppState: runs on both on the client and the server

### ISSUE THREAD

**Issue by TeemoWan** [worona/meteorflux#14] opened 2015-10-20 04:46 UTC
I use kadira:flow-router and kadira:flow-router-ssr。

kadira:flow-router-ssr：Write your app in a place it's expose to both client and the server.

**Comment by LuisHerranz** [comment] 2015-10-20 11:21
Hi @TeemoWan 

What's the issue? Do you want AppState in the server?

**Comment by TeemoWan** [comment] 2015-10-22 01:57
yes，i use react and kadira:flow-router-ssr，Need to use on the server side

**Comment by LuisHerranz** [comment] 2015-10-22 09:22
Could you please share an example of an app with server side rendering? Are you using React or Blaze?  Do you need AppState to be reactive in the server side as well (I suppose you don't), or only mimic what is capable of in the client?

**Comment by TeemoWan** [comment] 2015-10-22 12:05
for example:

login.jsx:

Login = React.createClass({

  mixins: [ReactMeteorData],

  getInitialState() {
    AppState.set('Auth', {
      Login: {
        succeed: false,
        errorMessage: ''
      }
    });

    return {}
  },

  getMeteorData() {
    return {
      errorMessage: AppState.get('Auth.Login.errorMessage'),
      loggingIn: Meteor.loggingIn()
    }
  },

  render() {
    ...
  }
})

Dispatcher.register(
  function(action){
    switch(action.type){
      case 'GO_TO_LOGIN':
        ReactLayout.render(AuthLayout, { content: <Login /> });
        break;
      case 'LOGIN_SUCCEED':
        AppState.set('Auth.Login.succeed', true);
        break;
      case 'LOGIN_FAILED':
        AppState.set('Auth.Login.succeed', false);
        AppState.set('Auth.Login.errorMessage', action.error.reason);
        break;
    }
  }
);

Tracker.autorun(function(){
  var loginState = AppState.get('Auth.Login.succeed');
  if (loginState) {
    Dispatcher.dispatch({ type: 'GO_TO_HOME' });
  }
});

**Comment by LuisHerranz** [comment] 2015-10-22 12:57
Ok, so I guess you are fine with a version of `AppState` which is defined on the server and only sets and gets stuff, without reactivity, for the first render. Is that ok?

By the way, did you get a "Cannot dispatch in the middle of another dispatch" error with the `GO_TO_HOME` redirection and you avoided it using `AppState.set('Auth.Login.succeed', true);` or is this by design?

**Comment by TeemoWan** [comment] 2015-10-22 14:53
Thank you.

For the first render, if define a version of component on the server without reactivity, then most of components in the project need to define twice.  Is that good?

**Comment by LuisHerranz** [comment] 2015-10-23 14:37
> For the first render, if define a version of component on the server without reactivity, then most of components in the project need to define twice. Is that good?

Could you please explain this in a different way? I don't understand what you are trying to say.

**Comment by luisherranz** [comment] 2015-12-21 12:23
I will close this now but if you have any comment just reopen it.

**Closed by luisherranz** 2015-12-21 12:23 UTC
Labels: feedback needed
